import React from "react";
import "./LandingFooter.css";

const Footer = () => {
  return (
    <div className="footer">
        &copy; {new Date().getFullYear()} Driver's Crash Course

        <div className="footer-right">
            Image generated by OpenAI's DALL-E
      </div>
    </div>
    
  );
};

export default Footer;
